stages:
- stage: RePlan
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: Apply
  condition: and(not(canceled()), not(eq(dependencies.Apply.result, 'Skipped')), eq(dependencies.Plan.outputs['Evaluate.Variable.ShouldRun'], 'true'))
  jobs:
  
  # Delay Job
  - template: ../Jobs/delay.yml

  # Plan Jobs
  - template: ../Jobs/replan.yml